### ISSUE TITLE
Feature idea: Send command w/o executing it

### ISSUE THREAD

**Issue by ThiefMaster** [tmux-python/tmuxp#735] opened 2022-02-07 14:07 UTC
I have some `ssh whatever` commands in my tmuxp config; and some of those require multi-factor auth so running them automatically when launching the session is not great.

Currently I use workarounds such as `read && ssh whatever` so the ssh command doesn't run immediately, but I think an option to just send the command but not the ENTER key to actually execute it would be much nicer.

**Comment by tony** [comment] 2022-02-07 16:14
@ThiefMaster I am considering adding something for this.  Have a suggestion for what the yaml should look like? e.g. `send_keys: false` in the command of a pane?

P.S. Have you tried this? https://github.com/tmux-python/tmuxp/issues/293#issuecomment-859782873

cc: https://github.com/tmux-python/tmuxp/issues/293

**Comment by tony** [comment] 2022-02-07 16:38
We will add that soon then

Did you try adding a `\` to the end of the command yet?

**Comment by tony** [comment] 2022-02-07 16:39
Did you try adding a `\` to the end of the command yet?

**Comment by ThiefMaster** [comment] 2022-02-07 16:39
nope - but in any case that would require changing something (e.g. deleting the backspace) just like my `read && ` workaround ;)

**Comment by tony** [comment] 2022-02-07 16:40
Got it

`send_keys: false` will be simple enough to add and will resolve this and #293

**Comment by thiagowfx** [comment] 2022-02-15 20:51
`send_keys: false` sounds sensible / reasonable. `dry-run: true` is an alternative I'd suggest.

**Comment by tony** [comment] 2022-03-12 18:25
@ThiefMaster @thiagowfx 

I am going to move this to the oldest issue

Duplicate of #53

**Closed** 2022-03-12 18:26 UTC
Labels: enhancement

**Comment by tony** [comment] 2022-03-12 22:09
@ThiefMaster (and @thiagowfx also re-tagging you since you are watching here and #53)

Live in 1.10.0b1 [pypi](https://pypi.org/project/tmuxp/1.10.0b1/) [branch](https://github.com/tmux-python/tmuxp/tree/v1.10.0b1)

`pip install --user --upgrade tmuxp==1.10.0b1`

or `pipx install --suffix=@1.10.0b1 'tmuxp==1.10.0b1'`  then `tmuxp@1.10.0b1 load <yaml file>`

docs: [skip command execution](https://tmuxp.git-pull.com/examples.html#skip-command-execution)

```yaml
session_name: Should not execute
windows:
- panes:
  - shell_command: echo "___$((1 + 3))___"
    enter: false
```
